server:
  port: 1000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SampleDB
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: DEPARTMENT-SERVICE

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/